"""The one place TER report colours are defined.

Every colour is a *role* with a light and a dark value. SVG primitives write
the light hex as a presentation attribute (so a standalone ``.svg`` file
renders on its own) plus a ``ter-f-<role>`` / ``ter-s-<role>`` class. The
HTML report's stylesheet, generated by :func:`stylesheet`, maps those classes
to CSS variables, which switch to the dark values under
``prefers-color-scheme: dark``.

The categorical slots are the validated, colour-vision-deficiency-safe order
used by ``ter visualize`` (PR #31): adjacent pairs clear CVD Delta E 8 in both
modes. Aligned work is blue and waste is red, the two poles of the diverging
pair, so the pair also reads for red-green colour-blind readers; waste marks
additionally carry a hatch texture so colour is never the only cue.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Colour:
    """A colour role: fill for marks, and the text colour that sits on it."""

    light: str
    dark: str
    on_light: str = "#0b0b0b"
    on_dark: str = "#ffffff"


#: Categorical slots, fixed order, never cycled past eight.
SERIES: tuple[Colour, ...] = (
    Colour("#2a78d6", "#3987e5", "#ffffff", "#ffffff"),  # 1 blue
    Colour("#eb6834", "#d95926", "#0b0b0b", "#ffffff"),  # 2 orange
    Colour("#1baf7a", "#199e70", "#0b0b0b", "#ffffff"),  # 3 aqua
    Colour("#eda100", "#c98500", "#0b0b0b", "#0b0b0b"),  # 4 yellow
    Colour("#e87ba4", "#d55181", "#0b0b0b", "#ffffff"),  # 5 magenta
    Colour("#008300", "#008300", "#ffffff", "#ffffff"),  # 6 green
    Colour("#4a3aa7", "#9085e9", "#ffffff", "#0b0b0b"),  # 7 violet
    Colour("#e34948", "#e66767", "#0b0b0b", "#0b0b0b"),  # 8 red
)

#: Light hex values of the categorical slots, in order (``ter visualize``'s PALETTE).
PALETTE: tuple[str, ...] = tuple(c.light for c in SERIES)

#: Every named role. Series slots are ``series-1`` … ``series-8``.
ROLES: dict[str, Colour] = {
    "surface": Colour("#fcfcfb", "#1a1a19"),
    "ink": Colour("#0b0b0b", "#ffffff"),
    "ink-2": Colour("#52514e", "#c3c2b7"),
    "muted": Colour("#6f6d68", "#a3a19a"),
    "grid": Colour("#e1e0d9", "#33332f"),
    "baseline": Colour("#c3c2b7", "#52514e"),
    "aligned": SERIES[0],
    "waste": SERIES[7],
    **{f"series-{i + 1}": c for i, c in enumerate(SERIES)},
}

#: Colour of each span label, matching ``ter visualize``'s composition chart.
LABEL_ROLES: dict[str, str] = {
    "aligned_reasoning": "series-1",
    "aligned_tool_call": "series-2",
    "aligned_response": "series-3",
    "redundant_reasoning": "series-4",
    "unnecessary_tool_call": "series-5",
    "over_explanation": "series-6",
}
OTHER_LABEL_ROLE = "series-7"

#: Colour of each phase.
PHASE_ROLES: dict[str, str] = {
    "reasoning": "series-1",
    "tool_use": "series-2",
    "generation": "series-3",
}
OTHER_PHASE_ROLE = "series-4"

_HEX_TO_ROLE: dict[str, str] = {
    c.light: f"series-{i + 1}" for i, c in enumerate(SERIES)
}


def resolve(colour: str) -> tuple[str, str | None]:
    """Return ``(light hex, role)`` for a role name or a hex value.

    A hex that matches a categorical slot resolves to that slot's role, so
    callers passing raw ``PALETTE`` values still get dark-mode styling.
    """
    if colour in ROLES:
        return ROLES[colour].light, colour
    return colour, _HEX_TO_ROLE.get(colour.lower())


def on_colour(colour: str) -> tuple[str, str | None]:
    """Return ``(light hex, role)`` for text drawn on top of ``colour``."""
    _, role = resolve(colour)
    if role is None:
        return "#ffffff", None
    return ROLES[role].on_light, f"on-{role}"


def stylesheet(selector: str = ".ter-chart") -> str:
    """CSS mapping role classes to variables, with light and dark values."""
    light: list[str] = []
    dark: list[str] = []
    rules: list[str] = []
    for role, c in ROLES.items():
        light.append(f"--ter-{role}:{c.light};--ter-on-{role}:{c.on_light}")
        dark.append(f"--ter-{role}:{c.dark};--ter-on-{role}:{c.on_dark}")
        rules.append(
            f"{selector} .ter-f-{role}{{fill:var(--ter-{role})}}"
            f"{selector} .ter-s-{role}{{stroke:var(--ter-{role})}}"
            f"{selector} .ter-f-on-{role}{{fill:var(--ter-on-{role})}}"
        )
    return (
        f":root{{{';'.join(light)}}}\n"
        "@media (prefers-color-scheme: dark){:root:not([data-theme=light])"
        f"{{{';'.join(dark)}}}}}\n"
        f":root[data-theme=dark]{{{';'.join(dark)}}}\n"
        "@media print{:root,:root:not([data-theme=light]),:root[data-theme=dark]"
        f"{{{';'.join(light)}}}}}\n" + "\n".join(rules)
    )
