"""The pure TER domain: the Lean model of an agentic software session.

Nothing in this package performs IO or knows about a specific agent harness,
tokenizer or model vendor. Those arrive through ``ter.ports``.
"""

from __future__ import annotations

from .events import (
    Actor,
    Event,
    EventId,
    EventKind,
    Provenance,
    SessionTrace,
    TokenUsage,
    ToolCall,
    ToolKind,
    UnrecognisedRecord,
    make_event_id,
)
from .maturity import Maturity
from .pricing import (
    PriceEntry,
    PriceSchedule,
    Rates,
    TokenCounts,
    UnknownModelError,
    token_cost,
    usage_cost,
)
from .report import (
    EconomicsSummary,
    KeyMetrics,
    LabelTokens,
    PhaseScore,
    PositionalTer,
    Reliability,
    ReportSection,
    SessionReport,
    SpanCell,
    UncertaintySummary,
    WasteByType,
    WasteEntry,
)
from .scoring import (
    DEFAULT_PHASE_WEIGHTS,
    PHASES,
    EfficiencyScore,
    ScoredSpan,
    score_spans,
    validate_phase_weights,
)
from .stream import (
    AnalysisEngine,
    EventClass,
    Signal,
    Signals,
    StreamReport,
    TimelineRow,
    TokenCounter,
    analyse_batch,
    explain_batch,
)

__all__ = [
    "Actor",
    "AnalysisEngine",
    "DEFAULT_PHASE_WEIGHTS",
    "EconomicsSummary",
    "EfficiencyScore",
    "Event",
    "EventClass",
    "EventId",
    "EventKind",
    "KeyMetrics",
    "LabelTokens",
    "Maturity",
    "PHASES",
    "PhaseScore",
    "PositionalTer",
    "PriceEntry",
    "PriceSchedule",
    "Provenance",
    "Rates",
    "Reliability",
    "ReportSection",
    "ScoredSpan",
    "SessionReport",
    "SessionTrace",
    "Signal",
    "Signals",
    "SpanCell",
    "StreamReport",
    "TimelineRow",
    "TokenCounter",
    "TokenCounts",
    "TokenUsage",
    "ToolCall",
    "ToolKind",
    "UncertaintySummary",
    "UnknownModelError",
    "UnrecognisedRecord",
    "WasteByType",
    "WasteEntry",
    "analyse_batch",
    "explain_batch",
    "make_event_id",
    "score_spans",
    "token_cost",
    "usage_cost",
    "validate_phase_weights",
]
